group 'com.amap.flutter.csp_amap_flutter_location'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.4'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    namespace 'com.amap.flutter.csp_amap_flutter_location'
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 21
    }
    lintOptions {
        disable 'InvalidPackage'
    }
    dependencies {
        api 'com.amap.api:location:6.4.9'
    }
}
